import { createHash } from 'node:crypto';
// The global `ReadableStream` resolves to undici's declaration, which is not the
// one Node's `stream.Readable.fromWeb` accepts. Importing the declaration the
// consumer needs keeps the interface honest instead of casting at every call.
import type { ReadableStream as NodeReadableStream } from 'node:stream/web';
import { config } from '../config.js';

/**
 * Cloudinary has three resource types. Which one an asset belongs to is part of
 * its address, so it has to be recoverable from the content type alone rather
 * than stored: `download` is handed a storage key and the sniffed content type
 * from the evidence row, and nothing else.
 */
export type CloudinaryResourceType = 'image' | 'video' | 'raw';

const EXTENSION_BY_CONTENT_TYPE: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'application/pdf': 'pdf',
  'video/mp4': 'mp4',
  'video/quicktime': 'mov',
  'video/webm': 'webm',
};

export function cloudinaryResourceType(contentType: string): CloudinaryResourceType {
  if (contentType.startsWith('image/')) return 'image';
  if (contentType.startsWith('video/')) return 'video';
  if (contentType === 'application/pdf') return 'raw';
  throw new RangeError(`Unsupported evidence content type for object storage: ${contentType}`);
}

export function extensionFor(contentType: string): string {
  const extension = EXTENSION_BY_CONTENT_TYPE[contentType];
  if (!extension) throw new RangeError(`Unsupported evidence content type for object storage: ${contentType}`);
  return extension;
}

/**
 * The storage key is already generated by the caller from the transaction id,
 * the idempotency key and the content checksum, so deriving the public id from
 * it keeps upload and download addressing stateless: there is no mapping table
 * to keep in step with the row, and a row written before a deploy still
 * resolves.
 *
 * The extension is part of the public id rather than a separate format field,
 * because the delivery URL has to name the format explicitly.
 */
export function cloudinaryPublicId(storageKey: string, contentType: string): string {
  return `${storageKey}.${extensionFor(contentType)}`;
}

/**
 * The string that is signed is exactly the path that follows the signature in
 * the delivery URL. Cloudinary's own worked example uses
 * `c_fill,w_300,h_250/e_grayscale/sample-authenticated.png` with the secret
 * `abcd`, producing the first eight characters `iDy_JeBq`.
 */
export function cloudinaryDeliverySignature(toSign: string, apiSecret: string): string {
  return createHash('sha1').update(toSign + apiSecret).digest('base64url').slice(0, 8);
}

/**
 * Builds a signed delivery URL for an `authenticated` asset.
 *
 * There is deliberately no expiry in this signature: Cloudinary derives it only
 * from the path and the API secret. A signed URL is therefore a permanent
 * capability for that asset, not a short-lived one, which is why
 * `download` streams the bytes through this service instead of handing the URL
 * to a client. Anyone holding the URL could read the evidence without being a
 * party to the transaction, and evidence is what a dispute is decided on.
 */
export function cloudinaryDeliveryUrl(cloudName: string, resourceType: CloudinaryResourceType, publicId: string, apiSecret: string): string {
  const signature = cloudinaryDeliverySignature(publicId, apiSecret);
  return `https://res.cloudinary.com/${cloudName}/${resourceType}/authenticated/s--${signature}--/${publicId}`;
}

export interface StoredObject {
  key: string;
  contentType: string;
  bytes: Buffer;
}

export interface ObjectStorage {
  put(key: string, bytes: Buffer, contentType: string): Promise<void>;
  /**
   * Returns a stream rather than a buffer. Evidence accepts 25 MB videos, and
   * buffering one per download inside the API process is how a handful of
   * concurrent requests exhausts memory on a small deploy instance.
   */
  get(key: string, contentType: string): Promise<NodeReadableStream<Uint8Array>>;
  remove(key: string, contentType: string): Promise<void>;
}

export class CloudinaryObjectStorage implements ObjectStorage {
  private readonly cloudName: string;
  private readonly apiKey: string;
  private readonly apiSecret: string;

  constructor() {
    if (!config.CLOUDINARY_CLOUD_NAME || !config.CLOUDINARY_API_KEY || !config.CLOUDINARY_API_SECRET) {
      throw new Error('Cloudinary is not configured');
    }
    this.cloudName = config.CLOUDINARY_CLOUD_NAME;
    this.apiKey = config.CLOUDINARY_API_KEY;
    this.apiSecret = config.CLOUDINARY_API_SECRET;
  }

  async put(key: string, bytes: Buffer, contentType: string): Promise<void> {
    const resourceType = cloudinaryResourceType(contentType);
    const body = new FormData();
    body.set('file', new Blob([new Uint8Array(bytes)], { type: contentType }), key);
    body.set('api_key', this.apiKey);
    // `authenticated` is what makes the asset private. A plain `upload` would be
    // readable by anyone who guessed or leaked the URL, which for evidence is
    // the same as publishing it.
    body.set('type', 'authenticated');
    body.set('public_id', cloudinaryPublicId(key, contentType));
    body.set('overwrite', 'true');

    const response = await fetch(`https://api.cloudinary.com/v1_1/${this.cloudName}/${resourceType}/upload`, {
      method: 'POST',
      headers: { Authorization: this.authorization() },
      body,
      signal: AbortSignal.timeout(60_000),
    });
    if (!response.ok) {
      throw new Error(`Cloudinary upload failed (${response.status})`);
    }
  }

  async get(key: string, contentType: string): Promise<NodeReadableStream<Uint8Array>> {
    const url = cloudinaryDeliveryUrl(
      this.cloudName,
      cloudinaryResourceType(contentType),
      cloudinaryPublicId(key, contentType),
      this.apiSecret,
    );
    // No timeout signal here: it would abort the response body part-way through
    // a large video rather than bounding the time to first byte.
    const response = await fetch(url, { headers: { Authorization: this.authorization() } });
    if (!response.ok || !response.body) {
      throw new Error(`Cloudinary download failed (${response.status})`);
    }
    // `fetch` types the body as undici's ReadableStream while Node's
    // `stream.Readable.fromWeb` is declared against `stream/web`'s. They are the
    // same runtime object and the same bytes; only the two declarations differ.
    return response.body as unknown as NodeReadableStream<Uint8Array>;
  }

  async remove(key: string, contentType: string): Promise<void> {
    const resourceType = cloudinaryResourceType(contentType);
    const response = await fetch(`https://api.cloudinary.com/v1_1/${this.cloudName}/${resourceType}/destroy`, {
      method: 'POST',
      headers: { Authorization: this.authorization(), 'Content-Type': 'application/json' },
      body: JSON.stringify({ public_id: cloudinaryPublicId(key, contentType), type: 'authenticated', invalidate: true }),
      signal: AbortSignal.timeout(30_000),
    });
    // Cloudinary answers 200 with an "error not found" payload when the asset
    // is already gone. The goal of this call is that the object is absent, so an
    // already-absent object is a success and must not fail the compensation.
    if (!response.ok) {
      throw new Error(`Cloudinary delete failed (${response.status})`);
    }
  }

  /**
   * Basic authentication rather than a request signature: the API key and
   * secret are enough to authenticate an upload, which removes a whole class of
   * "sorted the parameters wrong" failure from the write path.
   */
  private authorization(): string {
    return `Basic ${Buffer.from(`${this.apiKey}:${this.apiSecret}`).toString('base64')}`;
  }
}